version: '3.8'

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./shtatka:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgresql://postgres:u1710016@db:5432/shtatka_db

    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/web/shtatka/staticfiles/
      - media_volume:/web/shtatka/media/
    ports:
      - 1337:80
    depends_on:
      - web
    links:
      - web:web
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

#  certbot:
#    image: certbot/certbot:latest
#    volumes:
#      - ./certbot/www/:/var/www/certbot/:rw
#      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  postgres_data:
  static_volume:
  media_volume:

