"""role is changed

Revision ID: 001b9c19353c
Revises: bf6775dba4fc
Create Date: 2022-08-30 17:24:38.668534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001b9c19353c'
down_revision = 'bf6775dba4fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_roles', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='unique')
    # ### end Alembic commands ###
