"""client department and position

Revision ID: 097ab8d18167
Revises: aefcbc707ec5
Create Date: 2022-09-10 16:16:42.409435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097ab8d18167'
down_revision = 'aefcbc707ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
