"""client department and position

Revision ID: 12858576631b
Revises: e4392eda70ea
Create Date: 2022-09-10 16:07:41.848282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12858576631b'
down_revision = 'e4392eda70ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
