"""changing integer to decimal

Revision ID: 1408d89c40b8
Revises: 817b1edc97fe
Create Date: 2022-09-10 20:42:29.584769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1408d89c40b8'
down_revision = '817b1edc97fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_children', sa.Column('is_main', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_children', 'is_main')
    # ### end Alembic commands ###
