"""shtat_organization, shtat_department_user, shtat_department and shtat_department_organization models are added

Revision ID: 1556d2539b4b
Revises: 52632f3360eb
Create Date: 2022-08-30 11:29:21.665621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1556d2539b4b'
down_revision = '52632f3360eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shtat_departments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shtat_organizations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('organization_tin', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shtat_department_organizations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shtat_department_id', sa.INTEGER(), nullable=True),
    sa.Column('organization_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['shtat_organizations.id'], ),
    sa.ForeignKeyConstraint(['shtat_department_id'], ['shtat_departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shtat_department_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('shtat_department_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['shtat_department_id'], ['shtat_departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shtat_department_users')
    op.drop_table('shtat_department_organizations')
    op.drop_table('shtat_organizations')
    op.drop_table('shtat_departments')
    # ### end Alembic commands ###
