"""fixed

Revision ID: 2289c4c32aef
Revises: c2ac67e4abe3
Create Date: 2022-09-11 01:22:36.976920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2289c4c32aef'
down_revision = 'c2ac67e4abe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_department_positions', 'right_coefficient',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               type_=sa.FLOAT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_department_positions', 'right_coefficient',
               existing_type=sa.FLOAT(),
               type_=sa.NUMERIC(precision=5, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###
