"""status and type are added

Revision ID: 44db2275fc7f
Revises: 59a1a716bd4b
Create Date: 2022-09-23 21:45:39.094275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44db2275fc7f'
down_revision = '59a1a716bd4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    status_choice_enum = postgresql.ENUM('pending', 'checked', 'approved', 'finished', 'confirmed', name='statuschoice', create_type=False)
    status_choice_enum.create(op.get_bind(), checkfirst=True)

    type_choice_enum = postgresql.ENUM('with_self', 'with_budget', name='typechoice', create_type=False)
    type_choice_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('client_shtatkas', sa.Column('status', status_choice_enum, nullable=True))
    op.add_column('client_shtatkas', sa.Column('type', type_choice_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_shtatkas', 'type')
    op.drop_column('client_shtatkas', 'status')
    # ### end Alembic commands ###
