"""client department and position

Revision ID: 463d27af2a01
Revises: 6ca0272b275a
Create Date: 2022-09-10 15:58:29.347979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463d27af2a01'
down_revision = '6ca0272b275a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
