"""uuid is removed

Revision ID: 47d6274adf70
Revises: 940b8a3dddb6
Create Date: 2022-09-12 15:23:22.891341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d6274adf70'
down_revision = '940b8a3dddb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('organization_children_uuid_key', 'organization_children', type_='unique')
    op.drop_column('organization_children', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_children', sa.Column('uuid', sa.VARCHAR(length=2000), autoincrement=False, nullable=False))
    op.create_unique_constraint('organization_children_uuid_key', 'organization_children', ['uuid'])
    # ### end Alembic commands ###
