"""changed client_shtatkas

Revision ID: 55011d476b4b
Revises: 8a25c630dc71
Create Date: 2022-09-13 01:26:34.848142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55011d476b4b'
down_revision = '8a25c630dc71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_shtatkas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('child_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('chapter_code', sa.String(length=255), nullable=False),
    sa.Column('department_code', sa.String(length=255), nullable=False),
    sa.Column('small_department_code', sa.String(length=255), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('organization_children', sa.Column('client_shtatka_id', sa.INTEGER(), nullable=False))
    op.drop_constraint('organization_children_organization_shtatka_id_fkey', 'organization_children', type_='foreignkey')
    op.create_foreign_key(None, 'organization_children', 'client_shtatkas', ['client_shtatka_id'], ['id'])
    op.drop_column('organization_children', 'organization_shtatka_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_children', sa.Column('organization_shtatka_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'organization_children', type_='foreignkey')
    op.create_foreign_key('organization_children_organization_shtatka_id_fkey', 'organization_children', 'organization_shtatka', ['organization_shtatka_id'], ['id'])
    op.drop_column('organization_children', 'client_shtatka_id')
    op.drop_table('client_shtatkas')
    # ### end Alembic commands ###
