"""status is deleted

Revision ID: 59a1a716bd4b
Revises: 7e7442ce29a0
Create Date: 2022-09-23 21:44:40.138117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59a1a716bd4b'
down_revision = '7e7442ce29a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_shtatkas', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_shtatkas', sa.Column('status', postgresql.ENUM('pending', 'approved', 'confirmed', name='statuschoice'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
