"""regions and districts have been added

Revision ID: 5c6f067df9ec
Revises: 07c29165da57
Create Date: 2022-10-04 09:55:55.997064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c6f067df9ec'
down_revision = '07c29165da57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_shtatka_regions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('client_shtatka_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['client_shtatka_id'], ['client_shtatkas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_shtatka_districts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('client_shtatka_region_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['client_shtatka_region_id'], ['client_shtatka_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('client_shtatkas', 'type',
               existing_type=postgresql.ENUM('with_self', 'with_budget', name='typechoice'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_shtatkas', 'type',
               existing_type=postgresql.ENUM('with_self', 'with_budget', name='typechoice'),
               nullable=True)
    op.drop_table('client_shtatka_districts')
    op.drop_table('client_shtatka_regions')
    # ### end Alembic commands ###
