"""client department and position

Revision ID: 60fa1762db12
Revises: 463d27af2a01
Create Date: 2022-09-10 16:00:32.320785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60fa1762db12'
down_revision = '463d27af2a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
