"""role is changed

Revision ID: 678289b84199
Revises: 001b9c19353c
Create Date: 2022-08-30 17:28:09.124517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678289b84199'
down_revision = '001b9c19353c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
