"""permission name

Revision ID: 6ca0272b275a
Revises: 110236a472f6
Create Date: 2022-09-08 16:13:53.208263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca0272b275a'
down_revision = '110236a472f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'permissions', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permissions', type_='unique')
    # ### end Alembic commands ###
