"""region is changed

Revision ID: 6da4a9a39495
Revises: 5c6f067df9ec
Create Date: 2022-10-04 12:07:20.796197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6da4a9a39495'
down_revision = '5c6f067df9ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_shtatka_regions', sa.Column('organization_child_id', sa.INTEGER(), nullable=True))
    op.drop_constraint('client_shtatka_regions_client_shtatka_id_fkey', 'client_shtatka_regions', type_='foreignkey')
    op.create_foreign_key(None, 'client_shtatka_regions', 'organization_children', ['organization_child_id'], ['id'])
    op.drop_column('client_shtatka_regions', 'client_shtatka_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_shtatka_regions', sa.Column('client_shtatka_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'client_shtatka_regions', type_='foreignkey')
    op.create_foreign_key('client_shtatka_regions_client_shtatka_id_fkey', 'client_shtatka_regions', 'client_shtatkas', ['client_shtatka_id'], ['id'])
    op.drop_column('client_shtatka_regions', 'organization_child_id')
    # ### end Alembic commands ###
