"""changed client_shtatkas

Revision ID: 7a3e7f4068e3
Revises: 55011d476b4b
Create Date: 2022-09-13 01:29:40.038050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '7a3e7f4068e3'
down_revision = '55011d476b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    status_choice_enum = postgresql.ENUM('pending', 'approved', 'confirmed', name='statuschoice', create_type=False)
    status_choice_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('client_shtatkas', sa.Column('parent_id', sa.INTEGER(), nullable=False))
    op.add_column('client_shtatkas', sa.Column('status', status_choice_enum, nullable=True))
    op.create_foreign_key(None, 'client_shtatkas', 'shtat_organizations', ['parent_id'], ['id'])
    op.drop_column('client_shtatkas', 'address')
    op.drop_column('client_shtatkas', 'child_name')
    op.drop_column('client_shtatkas', 'small_department_code')
    op.drop_column('client_shtatkas', 'is_main')
    op.drop_column('client_shtatkas', 'chapter_code')
    op.drop_column('client_shtatkas', 'department_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_shtatkas', sa.Column('department_code', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('client_shtatkas', sa.Column('chapter_code', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('client_shtatkas', sa.Column('is_main', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('client_shtatkas', sa.Column('small_department_code', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('client_shtatkas', sa.Column('child_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('client_shtatkas', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'client_shtatkas', type_='foreignkey')
    op.drop_column('client_shtatkas', 'status')
    op.drop_column('client_shtatkas', 'parent_id')
    # ### end Alembic commands ###
