"""status change check

Revision ID: 7e7442ce29a0
Revises: aab02fc37a24
Create Date: 2022-09-23 21:41:31.777296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e7442ce29a0'
down_revision = 'aab02fc37a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_shtatkas', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_shtatkas', sa.Column('type', postgresql.ENUM('with_self', 'with_budget', name='typechoice'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
