"""role is changed

Revision ID: 7f3f23428b47
Revises: c5d754f8f420
Create Date: 2022-08-30 17:32:12.609678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3f23428b47'
down_revision = 'c5d754f8f420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
