"""user permission model

Revision ID: 87ba3561ce92
Revises: aad0c2ad0055
Create Date: 2022-09-08 14:42:46.218362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ba3561ce92'
down_revision = 'aad0c2ad0055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
