"""organization_shtatka has been added

Revision ID: 8a25c630dc71
Revises: 47d6274adf70
Create Date: 2022-09-12 17:42:55.470122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a25c630dc71'
down_revision = '47d6274adf70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    status_choice_enum = postgresql.ENUM('pending', 'approved', 'confirmed', name='statuschoice', create_type=False)
    status_choice_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('organization_shtatka',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('parent_id', sa.INTEGER(), nullable=False),
    sa.Column('status', status_choice_enum, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['shtat_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('organization_children', sa.Column('organization_shtatka_id', sa.INTEGER(), nullable=False))
    op.drop_constraint('organization_children_parent_id_fkey', 'organization_children', type_='foreignkey')
    op.create_foreign_key(None, 'organization_children', 'organization_shtatka', ['organization_shtatka_id'], ['id'])
    op.drop_column('organization_children', 'parent_id')
    op.drop_column('organization_children', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_children', sa.Column('status', postgresql.ENUM('pending', 'approved', 'confirmed', name='statuschoice'), autoincrement=False, nullable=True))
    op.add_column('organization_children', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'organization_children', type_='foreignkey')
    op.create_foreign_key('organization_children_parent_id_fkey', 'organization_children', 'shtat_organizations', ['parent_id'], ['id'])
    op.drop_column('organization_children', 'organization_shtatka_id')
    op.drop_table('organization_shtatka')
    # ### end Alembic commands ###
