"""uuid is added

Revision ID: 940b8a3dddb6
Revises: b91ae0c0a202
Create Date: 2022-09-11 13:20:26.494626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940b8a3dddb6'
down_revision = 'b91ae0c0a202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_children', sa.Column('uuid', sa.String(length=2000), nullable=False))
    op.create_unique_constraint(None, 'organization_children', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_children', type_='unique')
    op.drop_column('organization_children', 'uuid')
    # ### end Alembic commands ###
