"""Constraint is added

Revision ID: 9a435f099a72
Revises: 1556d2539b4b
Create Date: 2022-08-30 16:35:24.800569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a435f099a72'
down_revision = '1556d2539b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shtat_department_organizations', 'shtat_department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shtat_department_organizations', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shtat_department_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shtat_department_users', 'shtat_department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shtat_departments', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('shtat_departments', 'code',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.create_unique_constraint(None, 'shtat_departments', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shtat_departments', type_='unique')
    op.alter_column('shtat_departments', 'code',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('shtat_departments', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('shtat_department_users', 'shtat_department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('shtat_department_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('shtat_department_organizations', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('shtat_department_organizations', 'shtat_department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
