"""position_count

Revision ID: aab02fc37a24
Revises: 019ca5324d95
Create Date: 2022-09-20 14:43:45.497402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab02fc37a24'
down_revision = '019ca5324d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_department_positions', sa.Column('position_count', sa.INTEGER(), nullable=False))
    op.drop_column('client_department_positions', 'count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_department_positions', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('client_department_positions', 'position_count')
    # ### end Alembic commands ###
