"""client department and position

Revision ID: aefcbc707ec5
Revises: 12858576631b
Create Date: 2022-09-10 16:15:32.416799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aefcbc707ec5'
down_revision = '12858576631b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
