"""fixed

Revision ID: b91ae0c0a202
Revises: 2289c4c32aef
Create Date: 2022-09-11 01:24:01.807572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91ae0c0a202'
down_revision = '2289c4c32aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_department_positions', 'razryad_coefficient',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               type_=sa.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_department_positions', 'razryad_coefficient',
               existing_type=sa.FLOAT(),
               type_=sa.NUMERIC(precision=5, scale=3),
               existing_nullable=False)
    # ### end Alembic commands ###
