"""autoincrement is messed

Revision ID: bf6775dba4fc
Revises: 9a435f099a72
Create Date: 2022-08-30 17:23:26.954503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf6775dba4fc'
down_revision = '9a435f099a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shtat_department_organizations_shtat_department_id_fkey', 'shtat_department_organizations', type_='foreignkey')
    op.create_foreign_key(None, 'shtat_department_organizations', 'shtat_departments', ['shtat_department_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('shtat_department_users_shtat_department_id_fkey', 'shtat_department_users', type_='foreignkey')
    op.create_foreign_key(None, 'shtat_department_users', 'shtat_departments', ['shtat_department_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shtat_department_users', type_='foreignkey')
    op.create_foreign_key('shtat_department_users_shtat_department_id_fkey', 'shtat_department_users', 'shtat_departments', ['shtat_department_id'], ['id'])
    op.drop_constraint(None, 'shtat_department_organizations', type_='foreignkey')
    op.create_foreign_key('shtat_department_organizations_shtat_department_id_fkey', 'shtat_department_organizations', 'shtat_departments', ['shtat_department_id'], ['id'])
    # ### end Alembic commands ###
