"""role is changed

Revision ID: bfe059feeebf
Revises: 7f3f23428b47
Create Date: 2022-08-30 17:36:11.399035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe059feeebf'
down_revision = '7f3f23428b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
