"""role is changed

Revision ID: c5d754f8f420
Revises: 678289b84199
Create Date: 2022-08-30 17:29:55.118844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d754f8f420'
down_revision = '678289b84199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
