"""position and department models have been added

Revision ID: db96a3431079
Revises: 097ab8d18167
Create Date: 2022-09-10 17:09:40.101660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db96a3431079'
down_revision = '097ab8d18167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_children',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('child_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('chapter_code', sa.String(length=255), nullable=False),
    sa.Column('department_code', sa.String(length=255), nullable=False),
    sa.Column('small_department_code', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['shtat_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_departments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('total_count', sa.INTEGER(), nullable=False),
    sa.Column('total_minimal_salary', sa.INTEGER(), nullable=False),
    sa.Column('total_bonus_salary', sa.INTEGER(), nullable=False),
    sa.Column('total_base_salary', sa.INTEGER(), nullable=False),
    sa.Column('child_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['organization_children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_departments')
    op.drop_table('organization_children')
    # ### end Alembic commands ###
