"""is_republic is added

Revision ID: db97ee8bbc0b
Revises: 6da4a9a39495
Create Date: 2022-10-06 09:41:25.504666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db97ee8bbc0b'
down_revision = '6da4a9a39495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_children', sa.Column('is_republic', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_children', 'is_republic')
    # ### end Alembic commands ###
