"""client department and position

Revision ID: e4392eda70ea
Revises: 60fa1762db12
Create Date: 2022-09-10 16:04:22.277964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4392eda70ea'
down_revision = '60fa1762db12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
